include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true 
    strict-inference: false 
    strict-raw-types: false 

linter:
  rules:
    prefer_asserts_with_message: true 
    cascade_invocations: true
    hash_and_equals: true
    implicit_reopen: true
    cancel_subscriptions: true
    close_sinks: true
    avoid_web_libraries_in_flutter: true
    avoid_type_to_string: true
    avoid_relative_lib_imports: false 
    avoid_empty_else: true
    unnecessary_statements: true
    prefer_const_declarations: true
    use_string_buffers: false 
    valid_regexps: true
    control_flow_in_finally: true
    always_specify_types: true 

