name: novident_nodes
description: "An internal Novident package for export common Nodes"
version: 1.0.4
documentation: https://github.com/Novident/novident-nodes/issues/
repository: https://github.com/Novident/novident-nodes/
homepage: https://github.com/Novident/novident-nodes/
issue_tracker: https://github.com/Novident/novident-nodes/issues/
topics: [novident, nodes, internal]

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.16.0
  collection: ^1.19.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
